const NEW_MESSAGE = 'NEW_MESSAGE'
const CREATE_CHATROOM = 'CREATE_CHATROOM'
const JOIN_CHATROOM = 'JOIN_CHATROOM'
const LEAVE_CHATROOM = 'LEAVE_CHATROOM'


module.exports = {
  NEW_MESSAGE,
  CREATE_CHATROOM,
  JOIN_CHATROOM,
  LEAVE_CHATROOM
}