version: '3.8'
services:
  server:
    container_name: server
    build: ./server
    ports:
      - '9090:9090'
    environment:
      - PORT=9090
      - REDIS_URL=redis://cache
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    volumes:
      - ./server:/usr/src/server
    depends_on:
      - cache
  client:
    container_name: client
    build: ./client
    ports:
      - '9091:9091'
    environment:
      - PORT=9091
      - NEXT_PUBLIC_WEBSOCKET_PATH=ws://localhost:9090
      - NEXT_PUBLIC_SERVER_PATH=http://localhost:9090
    volumes:
      # Next.js Hot Refresh fix: https://jameschambers.co.uk/nextjs-hot-reload-docker-development
      - ./client:/usr/src/client
      - /usr/src/client/node_modules
      - /usr/src/client/.next
    depends_on:
      - server
  cache:
    container_name: cache
    image: redis:7-alpine3.16
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./cache:/usr/src/cache