const SOCKET_EVENT = Object.freeze({
  ROOM: Object.freeze({
    CREATE: 'CREATE_ROOM',
    JOIN: 'JOIN_ROOM',
    LEAVE: 'LEAVE_ROOM'
  }),
  MESSAGE: Object.freeze({
    SEND: 'SEND_MESSAGE',
    RECEIVE: 'RECEIVE_MESSAGE'
  }),
  WHISPER: Object.freeze({
    SEND: 'SEND_WHISPER',
    RECEIVE: 'RECEIVE_WHISPER'
  }),
  INFO: Object.freeze({
    INVALID_SOCKET_EVENT: 'INFO_INVALID_SOCKET_EVENT',
    ROOM_EXISTS: 'INFO_ROOM_EXISTS',
    ROOM_NOT_EXIST: 'INFO_ROOM_NOT_EXIST',
    INCORRECT_ROOM_PASSWORD: 'INFO_INCORRECT_ROOM_PASSWORD',
    USER_ALREADY_IN_ROOM: 'USER_ALREADY_IN_ROOM',
    USER_NOT_IN_ROOM: 'INFO_USER_NOT_IN_ROOM',
    USER_CONNECTED: 'INFO_USER_CONNECTED',
    USER_DISCONNECTED: 'INFO_USER_DISCONNECTED'
  })
});

export default SOCKET_EVENT;
